# Generated by Django 4.2 on 2023-07-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetflixTitles",
            fields=[
                ("index", models.BigIntegerField(primary_key=True, serialize=False)),
                ("show_id", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("director", models.TextField(blank=True, null=True)),
                ("cast", models.TextField(blank=True, null=True)),
                ("country", models.TextField(blank=True, null=True)),
                ("date_added", models.TextField(blank=True, null=True)),
                ("release_year", models.BigIntegerField(blank=True, null=True)),
                ("rating", models.TextField(blank=True, null=True)),
                ("duration", models.TextField(blank=True, null=True)),
                ("listed_in", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "netflix_titles",
                "managed": False,
            },
        ),
    ]
